version: "3.9"

services:
  s3-server:
    image: tectoro/s3-server:0.1-dev-12.1
    container_name: s3-server
    restart: always
    ports:
      - '35900:8000'
    volumes:
      - s3server_data:/data
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_BUCKET=${DEFAULT_BUCKET}

volumes:
  s3server_data:
