version: "3.9"

services:
  nats:
    image: nats:2.9.17
    container_name: nats
    restart: always
    command: [ "-js" ]
    ports:
      - '35600:4222'
    volumes: 
      - nats_data:/data/db
volumes: 
   nats_data:
