---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: android-api
  labels:
    app: android-api
spec:
  selector:
    matchLabels:
      app: android-api
  replicas: ${ANDROID_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: android-api
    spec:
      containers:
        - name: android-api
          image: registry.digitalocean.com/tectoro/android-api:${ANDROID_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: android-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 100Mi
              cpu: "50m"
            requests:
              memory: 90Mi
              cpu: "50m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: android-api
spec:
  selector:
    app: android-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
