---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: files
  labels:
    app: files
spec:
  selector:
    matchLabels:
      app: files
  replicas: ${FILES_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
        - name: files
          image: registry.digitalocean.com/tectoro/files-api:${FILES_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: files
          ports:
            - containerPort: 35010
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: files
spec:
  selector:
    app: files
  ports:
    - protocol: TCP
      port: 35010
      targetPort: 35010
  type: ClusterIP
---
