---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm
  labels:
    app: idm
spec:
  selector:
    matchLabels:
      app: idm
  replicas: ${IDM_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: idm
    spec:
      containers:
        - name: idm
          image: registry.digitalocean.com/tectoro/idm:${IDM_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: idm
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 50Mi
              cpu: "20m"
            requests:
              memory: 10Mi
              cpu: "10m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: idm
spec:
  selector:
    app: idm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
