---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-api
  namespace: ${NAMESPACE}
  labels:
    app: messages-api
spec:
  selector:
    matchLabels:
      app: messages-api
  replicas: ${MESSAGES_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: messages-api
    spec:
      containers:
        - name: messages-api
          image: registry.digitalocean.com/tectoro/messages-api:${MESSAGES_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: messagesapi
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 100Mi
              cpu: "20m"
            requests:
              memory: 50Mi
              cpu: "10m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: messages-api
spec:
  selector:
    app: messages-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
