---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-ui
  labels:
    app: nats-ui
spec:
  selector:
    matchLabels:
      app: nats-ui
  replicas: ${MONITORING_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: nats-ui
    spec:
      containers:
        - name: nats-ui
          image: registry.digitalocean.com/tectoro/nats-ui:${MONITORING_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: nats-ui
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: 50Mi
          #     cpu: "20m"
          #   requests:
          #     memory: 10Mi
          #     cpu: "10m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: nats-ui
spec:
  selector:
    app: nats-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
