---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines
  labels:
    app: pipelines
spec:
  selector:
    matchLabels:
      app: pipelines
  replicas: ${PIPELINES_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      containers:
        - name: pipelines
          image: registry.digitalocean.com/tectoro/mdm-pipelines:${PIPELINES_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: pipelines
          # resources:
          #   limits:
          #     memory: 750Mi
          #     cpu: "1000m"
          #   requests:
          #     memory: 250Mi
          #     cpu: "250m"
      imagePullSecrets:
        - name: doregistry
---
