---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  labels:
    app: reporting
spec:
  selector:
    matchLabels:
      app: reporting
  replicas: ${REPORTING_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: registry.digitalocean.com/tectoro/reporting:${REPORTING_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: reporting
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 50Mi
              cpu: "20m"
            requests:
              memory: 10Mi
              cpu: "10m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: reporting
spec:
  selector:
    app: reporting
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
