---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  labels:
    app: windows
spec:
  selector:
    matchLabels:
      app: windows
  replicas: ${WIN_API_REPLICAS}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: windows
    spec:
      containers:
        - name: windows
          image: registry.digitalocean.com/tectoro/windows-api:${WIN_API_IMAGE_VERSION}
          envFrom:
            - configMapRef:
                name: windowsapi
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: 50Mi
          #     cpu: "20m"
          #   requests:
          #     memory: 10Mi
          #     cpu: "10m"
      imagePullSecrets:
        - name: doregistry
---
apiVersion: v1
kind: Service
metadata:
  name: windows
spec:
  selector:
    app: windows
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---

